name: .NET Core Desktop

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install the .NET Core workload
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Create the app package by building and packaging the Windows Application Packaging project
      - name: Create the app package
        shell: pwsh
        run: ./build.ps1 -Version 5.0.0

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/TEdit*.zip"
          generateReleaseNotes: true


